### ISSUE TITLE
Sagemaker Studio auto shutdown extension not working with restrictive IAM policy

### ISSUE THREAD

**Issue by khanna-vijay** [aws-samples/sagemaker-studio-auto-shutdown-extension#5] opened 2021-04-02 06:47 UTC
This Extension works only when we give the IAM role of SageMakerAdmin, which is too open for a production. Could you please help to make it work with a restricted policy, and share the minimum IAM permissions required to make this work.

**Comment by rthamman** [comment] 2021-04-07 16:15
Hi Vijay, we are checking. Will circle back.

**Comment by rthamman** [comment] 2021-04-19 03:49
Vijay, I believe Andras reached out to you and this has been resolved. IAM permission has no implication on the extension. Let us know otherwise.

**Comment by garzoand** [comment] 2021-04-20 23:34
I am closing this issue as we were not able to reproduce. However, IAM permission should have no impact, I agree. If you will encounter with the same issue, please feel free to reopen.

**Closed by garzoand** 2021-04-20 23:34 UTC
